# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.10.5

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .

WORKDIR /dashboard
COPY . /dashboard

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN python3 -m nltk.downloader stopwords

CMD ["streamlit","run", "dashboard.py"]
