version: "3.7"

services:
    mysql:
      platform: linux/x86_64
      image: mysql:5.7
      ports:
        - 3308:3306
      volumes:
        - mysql-data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root#123
        MYSQL_DATABASE: twitter_data
        
    streamlit-dashboard:
      build: . 
      ports:
        - 8501:8501

volumes:
  mysql-data:
