name: GitHub Actions Test
on:
  push:
    branches:
      - "main"
      - "ci_cd"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.9, 3.10]

    steps:
        # Checkout the latest code from the repo
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Extract twitter files
        run: unzip data/global_twitter_data.zip -d data/
        # Setup which version of Python to use
      - name: Set Up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        # Display the Python version being used
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Install the Dependencies using pip
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest tests/test*
      # - name: Run docker-compose
      #   run: docker compose up -d
      - name: push docker login
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      #   run: docker compose up -d
      # - name: Cypress -tests
      #   uses: cypress-io/github-action@v2
      #   with: 
      #     wait-on: 'http://localhost:8501'
      - name: Clean up
        run: rm data/*.json
        